version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: posgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - nest_assignment
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: posgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - nest_assignment
networks:
  nest_assignment:
